### ISSUE TITLE
Balance reset to zero (MySQL)

### ISSUE THREAD

**Issue by MClausz** [lifehome/Fe#2]
I just installed your latest release and tested around, I tested with 2 accounts, one of them is OP account. And I noticed that sometimes my OP account's balance changed to 0 when I change server in my BungeeCord network (those servers use the same Fe MySQL database), the other account seems fine but however it's an worrisome. And I wonder is that a kind of "feature" or a bug?

**Comment by lifehome** [comment]
Sorry for miss out your issue, I and a few others on SpigotMC has confirmed this issue, and I am planning on a rewrite or somewhat. This plugin does NOT work anymore, and you should either stay tuned or opt for another economy plugin.

_Closing as repo is inactive._
